name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]  # Remove 16.x as it's EOL
      fail-fast: false  # Don't cancel other jobs if one fails
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run linter
      run: npm run lint
      continue-on-error: true  # Don't fail build on lint warnings
    
    - name: Run tests
      run: npm run test -- --reporter=verbose --bail=false
      timeout-minutes: 10  # Add timeout to prevent hanging
      env:
        NODE_ENV: test
        CI: true
    
    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      if: matrix.node-version == '20.x' && success()
      with:
        file: ./coverage/coverage-final.json
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false  # Don't fail if coverage upload fails
    
    - name: Build
      run: npm run build
      if: success()  # Only build if tests pass

- name: Use Node.js ${{ matrix.node-version }}
  uses: actions/setup-node@v4
  with:
    node-version: ${{ matrix.node-version }}
    # cache: 'npm'  # <-- Comment out or remove this line
